service: weather-app-backend

frameworkVersion: "^4.15.1"


provider:
  name: aws
  runtime: nodejs20.x
  region: ap-south-1
  environment:
    WEATHER_API_KEY: ${env:WEATHER_API_KEY}
    WEATHER_CACHE_TABLE: WeatherAppWeatherCache

useDotenv: true

functions:
  getWeatherByCoords:
    handler: src/controllers/weatherController.getWeatherByCoords
    events:
      - httpApi:
          path: /weather
          method: get

resources:
  Resources:
    WeatherCacheTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.WEATHER_CACHE_TABLE}
        AttributeDefinitions:
          - AttributeName: locationKey
            AttributeType: S
        KeySchema:
          - AttributeName: locationKey
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST

  # IAM permissions for Lambda to access DynamoDB
  # (Serverless adds these automatically for referenced tables, but you can be explicit)
  # Uncomment below if you want to be explicit:
  #  iamRoleStatements:
  #    - Effect: Allow
  #      Action:
  #        - dynamodb:GetItem
  #        - dynamodb:PutItem
  #      Resource:
  #        - arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.WEATHER_CACHE_TABLE}

custom:
  dotenv:
    basePath: ./
